# Generated by Django 4.0.4 on 2022-05-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='test',
            new_name='text',
        ),
    ]
